/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PudsAccordion {
    }
    interface PudsAccordionItem {
        "itemId": string;
        "itemTitle": string;
    }
    interface PudsChildTest {
        "isExpanded": boolean;
        "options": string[];
    }
    interface PudsMenuToggle {
        "isExpanded": boolean;
    }
}
declare global {
    interface HTMLPudsAccordionElement extends Components.PudsAccordion, HTMLStencilElement {
    }
    var HTMLPudsAccordionElement: {
        prototype: HTMLPudsAccordionElement;
        new (): HTMLPudsAccordionElement;
    };
    interface HTMLPudsAccordionItemElement extends Components.PudsAccordionItem, HTMLStencilElement {
    }
    var HTMLPudsAccordionItemElement: {
        prototype: HTMLPudsAccordionItemElement;
        new (): HTMLPudsAccordionItemElement;
    };
    interface HTMLPudsChildTestElement extends Components.PudsChildTest, HTMLStencilElement {
    }
    var HTMLPudsChildTestElement: {
        prototype: HTMLPudsChildTestElement;
        new (): HTMLPudsChildTestElement;
    };
    interface HTMLPudsMenuToggleElement extends Components.PudsMenuToggle, HTMLStencilElement {
    }
    var HTMLPudsMenuToggleElement: {
        prototype: HTMLPudsMenuToggleElement;
        new (): HTMLPudsMenuToggleElement;
    };
    interface HTMLElementTagNameMap {
        "puds-accordion": HTMLPudsAccordionElement;
        "puds-accordion-item": HTMLPudsAccordionItemElement;
        "puds-child-test": HTMLPudsChildTestElement;
        "puds-menu-toggle": HTMLPudsMenuToggleElement;
    }
}
declare namespace LocalJSX {
    interface PudsAccordion {
    }
    interface PudsAccordionItem {
        "itemId"?: string;
        "itemTitle"?: string;
    }
    interface PudsChildTest {
        "isExpanded"?: boolean;
        "options"?: string[];
    }
    interface PudsMenuToggle {
        "isExpanded"?: boolean;
    }
    interface IntrinsicElements {
        "puds-accordion": PudsAccordion;
        "puds-accordion-item": PudsAccordionItem;
        "puds-child-test": PudsChildTest;
        "puds-menu-toggle": PudsMenuToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "puds-accordion": LocalJSX.PudsAccordion & JSXBase.HTMLAttributes<HTMLPudsAccordionElement>;
            "puds-accordion-item": LocalJSX.PudsAccordionItem & JSXBase.HTMLAttributes<HTMLPudsAccordionItemElement>;
            "puds-child-test": LocalJSX.PudsChildTest & JSXBase.HTMLAttributes<HTMLPudsChildTestElement>;
            "puds-menu-toggle": LocalJSX.PudsMenuToggle & JSXBase.HTMLAttributes<HTMLPudsMenuToggleElement>;
        }
    }
}
